FROM golang
ADD kongExample /home/rcole/GolandProjects/GoLang-Learning/BuildingRestfulApis/docking/kongExample/
ENTRYPOINT /home/rcole/GolandProjects/GoLang-Learning/BuildingRestfulApis/docking/kongExample/kongExample

