package dbutils

const train = `
	CREATE TABLE IF NOT EXISTS train (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		DRIVER_NAME VARCHAR(64) NULL,
		OPERATING_STATUS BOOLEAN
	)
`

const station = `
	CREATE TABLE IF NOT EXISTS station (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		DRIVER_NAME VARCHAR(64) NULL,
		OPENING_TIME VARCHAR(64) NULL,
		CLOSING_TIME VARCHAR(64) NULL
	)
`

const schedule = `
	CREATE TABLE IF NOT EXISTS schedule (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		TRAIN_ID INT,
		STATION_ID INT,
		ARRIVAL_TIME VARCHAR(64),
		FOREIGN KEY (TRAIN_ID) REFERENCES train(ID),
		FOREIGN KEY (STATION_ID) REFERENCES station(ID)
	)
`
